/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlos López
 */
public class PanelCompraVenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelCompras
     */
    public PanelCompraVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comprasL = new javax.swing.JLabel();
        modeloL = new javax.swing.JLabel();
        marcaL = new javax.swing.JLabel();
        anoL = new javax.swing.JLabel();
        colorL = new javax.swing.JLabel();
        tamanoL = new javax.swing.JLabel();
        precioL = new javax.swing.JLabel();
        modeloTF = new javax.swing.JTextField();
        marcaTF = new javax.swing.JTextField();
        anoTF = new javax.swing.JTextField();
        colorTF = new javax.swing.JTextField();
        tamanoTF = new javax.swing.JTextField();
        precioTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ventasL = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1231, 1000));
        setMinimumSize(new java.awt.Dimension(1231, 1000));
        setPreferredSize(new java.awt.Dimension(1231, 1000));

        comprasL.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        comprasL.setText("Compras");

        modeloL.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        modeloL.setText("Modelo");

        marcaL.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        marcaL.setText("Marca");

        anoL.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        anoL.setText("Año");

        colorL.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        colorL.setText("Color");

        tamanoL.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        tamanoL.setText("Tamaño");

        precioL.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        precioL.setText("Precio");

        tamanoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanoTFActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        ventasL.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ventasL.setText("Ventas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marcaL)
                            .addComponent(anoL))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tamanoL)
                                .addGap(369, 369, 369))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(precioL)
                                .addGap(398, 398, 398))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(modeloL)
                        .addGap(65, 65, 65)
                        .addComponent(modeloTF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorL)
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tamanoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comprasL)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(175, 175, 175))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ventasL)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(comprasL)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modeloL)
                            .addComponent(colorL)))
                    .addComponent(colorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marcaL)
                            .addComponent(tamanoL)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(marcaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(tamanoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(anoL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(precioL)
                            .addComponent(anoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(ventasL)
                .addContainerGap(417, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tamanoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamanoTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoL;
    private javax.swing.JTextField anoTF;
    private javax.swing.JLabel colorL;
    private javax.swing.JTextField colorTF;
    private javax.swing.JLabel comprasL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel marcaL;
    private javax.swing.JTextField marcaTF;
    private javax.swing.JLabel modeloL;
    private javax.swing.JTextField modeloTF;
    private javax.swing.JLabel precioL;
    private javax.swing.JTextField precioTF;
    private javax.swing.JLabel tamanoL;
    private javax.swing.JTextField tamanoTF;
    private javax.swing.JLabel ventasL;
    // End of variables declaration//GEN-END:variables
}
