//Autores:
//Carlos Ernesto Lopez Solano A01633683
//Juan Daniel Rubio Camacho A01633924
//Nombre de la clase: PanelContratar.java
//Fecha: 05/05/2019
//Comentarios u observaciones.
//------------------------------------------------------------------------------

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


public class PanelContratar extends javax.swing.JPanel {
    
    private ImageIcon foto;
    private ListaEmpleados le;
    private PanelEmpleados pe;

    public PanelContratar(PanelEmpleados pe) {
        initComponents();
        this.le = DataLoader.loadEmployees(new File("EmployeeDatabase.bin"));
        this.pe = pe;
        this.foto = null;
    }
    
    private void vaciarCampos() {
        primerNombreTF.setText("");
        segundoNombreTF.setText("");
        apellidoPaternoTF.setText("");
        apellidoMaternoTF.setText("");
        rfcTF.setText("");
        cargoTF.setText("");
        archivoL.setText("Seleccionar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contratarL = new javax.swing.JLabel();
        contratarB = new javax.swing.JButton();
        primerNombreL = new javax.swing.JLabel();
        segundoNombreL = new javax.swing.JLabel();
        apellidoPaternoL = new javax.swing.JLabel();
        apellidoMaternoL = new javax.swing.JLabel();
        cargoL = new javax.swing.JLabel();
        fotoL = new javax.swing.JLabel();
        rfcL = new javax.swing.JLabel();
        selectFotoB = new javax.swing.JButton();
        archivoL = new javax.swing.JLabel();
        primerNombreTF = new javax.swing.JTextField();
        segundoNombreTF = new javax.swing.JTextField();
        apellidoPaternoTF = new javax.swing.JTextField();
        apellidoMaternoTF = new javax.swing.JTextField();
        cargoTF = new javax.swing.JTextField();
        rfcTF = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1231, 449));
        setMinimumSize(new java.awt.Dimension(1231, 449));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1231, 449));
        setRequestFocusEnabled(false);

        contratarL.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        contratarL.setText("Contratar");

        contratarB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        contratarB.setText("Contratar");
        contratarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarBActionPerformed(evt);
            }
        });

        primerNombreL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        primerNombreL.setText("Primer Nombre");

        segundoNombreL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        segundoNombreL.setText("Segundo Nombre");

        apellidoPaternoL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        apellidoPaternoL.setText("Apellido Paterno");

        apellidoMaternoL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        apellidoMaternoL.setText("Apellido Materno");

        cargoL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        cargoL.setText("Cargo");

        fotoL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        fotoL.setText("Foto");

        rfcL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        rfcL.setText("RFC");

        selectFotoB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectFotoB.setText("Elegir archivo");
        selectFotoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFotoBActionPerformed(evt);
            }
        });

        archivoL.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        archivoL.setText("Seleccionar");

        primerNombreTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        segundoNombreTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        apellidoPaternoTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        apellidoMaternoTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        cargoTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        rfcTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(apellidoMaternoL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contratarB))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contratarL)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primerNombreL)
                                    .addComponent(segundoNombreL)
                                    .addComponent(apellidoPaternoL))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellidoPaternoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(segundoNombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(primerNombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(87, 87, 87)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fotoL)
                                                .addGap(50, 50, 50)
                                                .addComponent(selectFotoB)
                                                .addGap(18, 18, 18)
                                                .addComponent(archivoL))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cargoL)
                                                    .addComponent(rfcL))
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rfcTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cargoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(apellidoMaternoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contratarL)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primerNombreL)
                    .addComponent(cargoL)
                    .addComponent(primerNombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segundoNombreL)
                    .addComponent(rfcL)
                    .addComponent(segundoNombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfcTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoPaternoL)
                    .addComponent(fotoL)
                    .addComponent(selectFotoB)
                    .addComponent(archivoL)
                    .addComponent(apellidoPaternoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contratarB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoMaternoL)
                            .addComponent(apellidoMaternoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void contratarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarBActionPerformed
        this.le = DataLoader.loadEmployees(new File("EmployeeDatabase.bin"));
        if(primerNombreTF.getText().equals("") || apellidoPaternoTF.getText().equals("") || apellidoMaternoTF.getText().equals("") ||
           rfcTF.getText().equals("") || cargoTF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los espacios son obligatorios excepto Segundo Nombre y Foto");
        } else if(!cargoTF.getText().equals("Gerente") && !cargoTF.getText().equals("Empleado")) {
            JOptionPane.showMessageDialog(this, "Por el momento solo existen las posiciones de Empleado y Gerente. Por favor seleccione una de las mismas");
        } else {
            Empleado nuevoEmpleado = new Empleado(primerNombreTF.getText(), segundoNombreTF.getText(), apellidoPaternoTF.getText(),
                                              apellidoMaternoTF.getText(), rfcTF.getText(), cargoTF.getText(), this.foto);
            nuevoEmpleado.generaMatricula(le);
            this.le.contratar(nuevoEmpleado);
            this.le.almacenarEmpleados();
            this.vaciarCampos();
            this.foto = null;
            JOptionPane.showMessageDialog(this, "La contratación ha sido exitosa");
            this.pe.actualizarTabla();
        }
    }//GEN-LAST:event_contratarBActionPerformed

    private void selectFotoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFotoBActionPerformed
    	this.le = DataLoader.loadEmployees(new File("EmployeeDatabase.bin"));
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("JPG, GIF and PNG Images", "jpg", "gif", "png"));
        int choosed = chooser.showOpenDialog(null);
        if(choosed == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedImage fotin = ImageIO.read(chooser.getSelectedFile());
                Image img = fotin.getScaledInstance(150, 30, Image.SCALE_SMOOTH);
                this.foto = new ImageIcon(img);
            } catch(IOException ex) {
                System.out.println("El archivo no pudo ser leido correctamente");
            }
            archivoL.setText(chooser.getSelectedFile().getName());
        } else if(choosed == JFileChooser.CANCEL_OPTION) {
            
        } else {
            JOptionPane.showMessageDialog(this, "Por favor intentelo de nuevo");
        }
    }//GEN-LAST:event_selectFotoBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoMaternoL;
    private javax.swing.JTextField apellidoMaternoTF;
    private javax.swing.JLabel apellidoPaternoL;
    private javax.swing.JTextField apellidoPaternoTF;
    private javax.swing.JLabel archivoL;
    private javax.swing.JLabel cargoL;
    private javax.swing.JTextField cargoTF;
    private javax.swing.JButton contratarB;
    private javax.swing.JLabel contratarL;
    private javax.swing.JLabel fotoL;
    private javax.swing.JLabel primerNombreL;
    private javax.swing.JTextField primerNombreTF;
    private javax.swing.JLabel rfcL;
    private javax.swing.JTextField rfcTF;
    private javax.swing.JLabel segundoNombreL;
    private javax.swing.JTextField segundoNombreTF;
    private javax.swing.JButton selectFotoB;
    // End of variables declaration//GEN-END:variables
}
