//Autores:
//Carlos Ernesto Lopez Solano A01633683
//Juan Daniel Rubio Camacho A01633924
//Nombre de la clase: PanelEditar.java
//Fecha: 05/05/2019
//Comentarios u observaciones.
//------------------------------------------------------------------------------

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.filechooser.FileNameExtensionFilter;


public class PanelEditar extends javax.swing.JPanel {
    
    private ImageIcon foto;
    private ListaEmpleados le;
    private Empleado empleadoSeleccionado;
    private PanelEmpleados pe;

    public PanelEditar(PanelEmpleados pe, Empleado empleado) {
        initComponents();
        this.le = DataLoader.loadEmployees(new File("EmployeeDatabase.bin"));
        this.foto = null;
        this.pe = pe;
        this.empleadoSeleccionado = empleado;
        this.llenarCampos(empleadoSeleccionado);
    }
    
    public void llenarCampos(Empleado empleado) {
        try {
            this.empleadoSeleccionado = empleado;
            this.primerNombreTF.setText(empleado.getPrimerNombre());
            this.segundoNombreTF.setText(empleado.getSegundoNombre());
            this.apellidoPaternoTF.setText(empleado.getApellidoPaterno());
            this.apellidoMaternoTF.setText(empleado.getApellidoMaterno());
            this.rfcTF.setText(empleado.getRfc());
            this.cargoTF.setText(empleado.getCargo());
            this.foto = null;
            this.matriculaTF.setText(empleado.getMatricula());
            this.contrasenaTF.setText(empleado.getContrasena());
            this.archivoL.setText(this.foto.toString());
        } catch(NullPointerException e) {
        	
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarL = new javax.swing.JLabel();
        despedirB = new javax.swing.JButton();
        primerNombreL = new javax.swing.JLabel();
        segundoNombreL = new javax.swing.JLabel();
        apellidoPaternoL = new javax.swing.JLabel();
        apellidoMaternoL = new javax.swing.JLabel();
        cargoL = new javax.swing.JLabel();
        fotoL = new javax.swing.JLabel();
        rfcL = new javax.swing.JLabel();
        selectFotoB = new javax.swing.JButton();
        archivoL = new javax.swing.JLabel();
        primerNombreTF = new javax.swing.JTextField();
        segundoNombreTF = new javax.swing.JTextField();
        apellidoPaternoTF = new javax.swing.JTextField();
        apellidoMaternoTF = new javax.swing.JTextField();
        cargoTF = new javax.swing.JTextField();
        rfcTF = new javax.swing.JTextField();
        editarB = new javax.swing.JButton();
        matriculaL = new javax.swing.JLabel();
        matriculaTF = new javax.swing.JTextField();
        contrasenaL = new javax.swing.JLabel();
        contrasenaTF = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1231, 449));
        setMinimumSize(new java.awt.Dimension(1231, 449));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1231, 449));
        setRequestFocusEnabled(false);

        editarL.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        editarL.setText("Editar");

        despedirB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        despedirB.setText("Despedir");
        despedirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirBActionPerformed(evt);
            }
        });

        primerNombreL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        primerNombreL.setText("Primer Nombre");

        segundoNombreL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        segundoNombreL.setText("Segundo Nombre");

        apellidoPaternoL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        apellidoPaternoL.setText("Apellido Paterno");

        apellidoMaternoL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        apellidoMaternoL.setText("Apellido Materno");

        cargoL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        cargoL.setText("Cargo");

        fotoL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        fotoL.setText("Foto");

        rfcL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        rfcL.setText("RFC");

        selectFotoB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectFotoB.setText("Elegir archivo");
        selectFotoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFotoBActionPerformed(evt);
            }
        });

        archivoL.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        archivoL.setText("Seleccionar");

        primerNombreTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        segundoNombreTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        apellidoPaternoTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        apellidoMaternoTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        cargoTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        rfcTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        editarB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        editarB.setText("Editar");
        editarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBActionPerformed(evt);
            }
        });

        matriculaL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        matriculaL.setText("Matrícula");

        matriculaTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        contrasenaL.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        contrasenaL.setText("Contraseña");

        contrasenaTF.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarL)
                        .addContainerGap(1054, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primerNombreL)
                                    .addComponent(segundoNombreL)
                                    .addComponent(apellidoPaternoL))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellidoPaternoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(segundoNombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(primerNombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(matriculaL)
                            .addComponent(apellidoMaternoL)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matriculaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidoMaternoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fotoL)
                                        .addGap(50, 50, 50)
                                        .addComponent(selectFotoB)
                                        .addGap(18, 18, 18)
                                        .addComponent(archivoL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cargoL)
                                            .addComponent(rfcL))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rfcTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cargoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(contrasenaL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(contrasenaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editarB)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(190, 190, 190)
                                        .addComponent(despedirB)))
                                .addGap(83, 83, 83))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editarL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargoL)
                            .addComponent(cargoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rfcL)
                            .addComponent(rfcTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fotoL)
                            .addComponent(selectFotoB)
                            .addComponent(archivoL))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contrasenaL)
                            .addComponent(contrasenaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(despedirB)
                            .addComponent(editarB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(primerNombreL)
                            .addComponent(primerNombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(segundoNombreL)
                            .addComponent(segundoNombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoPaternoL)
                            .addComponent(apellidoPaternoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoMaternoL)
                            .addComponent(apellidoMaternoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matriculaL)
                            .addComponent(matriculaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void despedirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirBActionPerformed
    	this.le = DataLoader.loadEmployees(new File("EmployeeDatabase.bin"));
        if (JOptionPane.showConfirmDialog(this, "Esta seguro de que desea despedir a " + this.empleadoSeleccionado.getPrimerNombre() + " " + this.empleadoSeleccionado.getApellidoPaterno()
                + "? Esta acción no se puede deshacer", "Despedir empleado?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            this.le.despedir(this.empleadoSeleccionado.getMatricula());
            this.le.almacenarEmpleados();
            this.pe.actualizarTabla();
            this.pe.casoBase();
        } 
    }//GEN-LAST:event_despedirBActionPerformed

    private void selectFotoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFotoBActionPerformed
    	this.le = DataLoader.loadEmployees(new File("EmployeeDatabase.bin"));
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("JPG, GIF and PNG Images", "jpg", "gif", "png"));
        int choosed = chooser.showOpenDialog(null);
        if(choosed == JFileChooser.APPROVE_OPTION) {
            try {
            	BufferedImage fotin = ImageIO.read(chooser.getSelectedFile());
                Image img = fotin.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                this.foto = new ImageIcon(img);
            } catch(IOException ex) {
                System.out.println("El archivo no pudo ser leido correctamente");
            }
            this.archivoL.setText(chooser.getSelectedFile().getName());
        } else if(choosed == JFileChooser.CANCEL_OPTION) {
            
        } else {
            JOptionPane.showMessageDialog(this, "Por favor intentelo de nuevo");
        }
    }//GEN-LAST:event_selectFotoBActionPerformed

    private void editarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBActionPerformed
    	this.le = DataLoader.loadEmployees(new File("EmployeeDatabase.bin"));
        Empleado empleadoEditado = new Empleado(this.primerNombreTF.getText(), this.segundoNombreTF.getText(), this.apellidoPaternoTF.getText(),
                                              this.apellidoMaternoTF.getText(), this.rfcTF.getText(), this.cargoTF.getText(), this.matriculaTF.getText(), this.contrasenaTF.getText(),  this.foto);
        
        if(empleadoEditado.equals(this.empleadoSeleccionado)) {
            JOptionPane.showMessageDialog(this, "No se realizaron cambios al empleado seleccionado");
        } else if(this.primerNombreTF.getText().equals("") || this.apellidoPaternoTF.getText().equals("") || this.apellidoMaternoTF.getText().equals("") ||
           this.rfcTF.getText().equals("") || this.cargoTF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los espacios son obligatorios excepto Segundo Nombre y Foto");
        } else if(!this.cargoTF.getText().equals("Gerente") && !this.cargoTF.getText().equals("Empleado")) {
            JOptionPane.showMessageDialog(this, "Por el momento solo existen las posiciones de Empleado y Gerente. Por favor seleccione una de las mismas");
        } else {
            this.le.modificarEmpleado(this.empleadoSeleccionado.getMatricula(), this.contrasenaTF.getText(), this.primerNombreTF.getText(), this.segundoNombreTF.getText(), this.apellidoPaternoTF.getText(),
                                              this.apellidoMaternoTF.getText(), this.rfcTF.getText(), this.cargoTF.getText(), this.foto);
            this.le.almacenarEmpleados();
            JOptionPane.showMessageDialog(this, "La edición ha sido exitosa");
            this.pe.actualizarTabla();
        }
    }//GEN-LAST:event_editarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoMaternoL;
    private javax.swing.JTextField apellidoMaternoTF;
    private javax.swing.JLabel apellidoPaternoL;
    private javax.swing.JTextField apellidoPaternoTF;
    private javax.swing.JLabel archivoL;
    private javax.swing.JLabel cargoL;
    private javax.swing.JTextField cargoTF;
    private javax.swing.JLabel contrasenaL;
    private javax.swing.JTextField contrasenaTF;
    private javax.swing.JButton despedirB;
    private javax.swing.JButton editarB;
    private javax.swing.JLabel editarL;
    private javax.swing.JLabel fotoL;
    private javax.swing.JLabel matriculaL;
    private javax.swing.JTextField matriculaTF;
    private javax.swing.JLabel primerNombreL;
    private javax.swing.JTextField primerNombreTF;
    private javax.swing.JLabel rfcL;
    private javax.swing.JTextField rfcTF;
    private javax.swing.JLabel segundoNombreL;
    private javax.swing.JTextField segundoNombreTF;
    private javax.swing.JButton selectFotoB;
    // End of variables declaration//GEN-END:variables
}
